### ISSUE TITLE
脱离HBuilder运行uniCloud

### ISSUE THREAD

**Issue by quanzaiyu** [Pidbid/uc#1]
我的uniapp项目是通过cli创建的，通过HBuilder初始化了uniCloud，但我习惯在VSCode中进行开发。运行uniCloud又必须通过HBuilder，本质上HBuilder也是执行某个命令运行的，但我并不知道是什么命令。请问有没有脱离HBuilder运行uniCloud的方法，直接在vscode的集成终端中就运行了，而不需要在HBuilder和vscode之间进行切换。

**Comment by Pidbid** [comment]
hbuilder cli 就是我这个工具的本质 了一查看cli的文档，但是uniCloud似乎无法脱离HB运行，官方并没有支持
